sudo: false

language: node_js

cache: npm

notifications:
  email: false

node_js: "10"

install: npm ci

script:
  - npm run lint
  - npm run test:with-coverage

# Will still run for PRs if configured
# in TravisCI UI options.
branches:
  only:
    - master
