// flow-typed signature: 0a10bab6b4e0bbbe86a74e3f68e4af77
// flow-typed version: <<STUB>>/semistandard_v^12.0.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'semistandard'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'semistandard' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'semistandard/bin/cmd' {
  declare module.exports: any;
}

declare module 'semistandard/options' {
  declare module.exports: any;
}

declare module 'semistandard/test/api' {
  declare module.exports: any;
}

declare module 'semistandard/test/clone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'semistandard/bin/cmd.js' {
  declare module.exports: $Exports<'semistandard/bin/cmd'>;
}
declare module 'semistandard/index' {
  declare module.exports: $Exports<'semistandard'>;
}
declare module 'semistandard/index.js' {
  declare module.exports: $Exports<'semistandard'>;
}
declare module 'semistandard/options.js' {
  declare module.exports: $Exports<'semistandard/options'>;
}
declare module 'semistandard/test/api.js' {
  declare module.exports: $Exports<'semistandard/test/api'>;
}
declare module 'semistandard/test/clone.js' {
  declare module.exports: $Exports<'semistandard/test/clone'>;
}
