// flow-typed signature: d56e69f73a90e218013424b7e01e6ecf
// flow-typed version: <<STUB>>/snazzy_v^7.1.1/flow_v0.75.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snazzy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snazzy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snazzy/bin/cmd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snazzy/bin/cmd.js' {
  declare module.exports: $Exports<'snazzy/bin/cmd'>;
}
declare module 'snazzy/index' {
  declare module.exports: $Exports<'snazzy'>;
}
declare module 'snazzy/index.js' {
  declare module.exports: $Exports<'snazzy'>;
}
